# Generated by Django 5.2.1 on 2025-05-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermodel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
